# This .yml file executes the .py file in the main branch. The aim of using GitHub actions is to automate the scrapping of tweets data


name: scrape_tweets

on:
  schedule:
    - cron: '0 0/1 * * *'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute python script
        run: python NigeriaDecides.py

      - name: Commit changes
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add .
          git commit -m "Today Scrapped"
          git pull origin new_branch
          # resolve any conflicts if necessary
          git add .
          git commit -m "Merge conflicts"
          git push origin new_branch
          
      - name: Pull repository  
        run: |
          git clone https://github.com/Retji/NigeriaDecides2023-DATA-SCRAPPING-AND-ANALYTICS.git
          cd NigeriaDecides2023-DATA-SCRAPPING-AND-ANALYTICS
          git pull origin main
          git checkout -b new_branch
          git add .
          git commit -m "Today Scrapped"
          git push --set-upstream origin new_branch
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Today Scrapped"
          branch: new_branch
          title: "Scraped data update"
          body: "This pull request contains updates to the scraped data."
          labels: "data update, automated"
