# This .yml file executes the .py file in the main branch. The aim of using GitHub actions is to automate the scrapping of tweets data


name: scrape_tweets

# Controls when the workflow will run
on:
  schedule:
        - cron: '0 0/1 * * *' #runs every 12 hour

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
          - name: checkout repo content
            uses: actions/checkout@v3 # checkout the repository content to github runner.
            
          - name: Set up python
            uses: actions/setup-python@v3
            with:
              python-version: "3.10"
              update-environment: false
              cache: 'pip'
         
          - name: Install dependencies
            run: |
              python -m pip install --upgrade pip
              pip install -r requirements.txt
              
          - name: Execute pyhon script
            run: python NigeriaDecides.py
            
          - name: Commit changes
            run: |
              git config --local user.name actions-user
              git config --local user.email "actions@github.com"
              git add -A
              git commit -m "Today Scrapped"
              git branch new_branch
              git checkout new_branch
              git push --set-upstream origin new_branch
            env: 
              REPO_KEY: ${{secrets.GITHUB_TOKEN}}
              username: github-actions
              
          - name: Create pull request
            uses: peter-evans/create-pull-request@v3
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
              commit-message: "Today Scrapped"
              branch: new_branch
              title: "Scraped data update"
              body: "This pull request contains updates to the scraped data."
              labels: "data update, automated"

